source "https://rubygems.org"

# see docs/inline/site/Gemfile.md#1
ruby ">= 3.2"

# see docs/inline/site/Gemfile.md#2

gem "jekyll", "~> 4.3"

# see docs/inline/site/Gemfile.md#3
gem "webrick", "~> 1.8"
gem "csv"
gem "base64"
gem "bigdecimal"
