// The price list the broker charges from.
//
// GENERATED by script/build-prices.py from _data/membership.yml and
// _data/classes.yml. Do not edit this file — edit those, run the script, and
// commit both. CI fails if the two disagree.
//
// Amounts are in cents, because that is what Stripe takes and because money
// in floating point eventually charges somebody $69.99999.
//
// Changing a price here is a commit, which is the point: `git log -p` on the
// data files is the price history, and a pull request is the announcement.

export default {
  "currency": "usd",
  "items": {
    "membership:creator": {
      "amount": 7000,
      "description": "One year from today. Renews on the day you joined, not in January.",
      "interval": "year",
      "kind": "membership",
      "name": "Creator membership"
    },
    "membership:producer": {
      "amount": 14000,
      "description": "One year from today. Renews on the day you joined, not in January.",
      "interval": "year",
      "kind": "membership",
      "name": "Producer membership"
    },
    "membership:sponsor": {
      "amount": 4000,
      "description": "One year from today. Renews on the day you joined, not in January.",
      "interval": "year",
      "kind": "membership",
      "name": "Sponsor membership"
    },
    "membership:student": {
      "amount": 6000,
      "description": "One year from today. Renews on the day you joined, not in January.",
      "interval": "year",
      "kind": "membership",
      "name": "Student membership"
    }
  }
};
