// GENERATED by site/bin/build-prices.py; do not edit. See docs/inline/worker/src/prices.js.md#1

export default {
  "currency": "usd",
  "items": {
    "membership:creator": {
      "amount": 7000,
      "description": "One year from today. Renews on the day you joined, not in January.",
      "interval": "year",
      "kind": "membership",
      "name": "Creator membership"
    },
    "membership:producer": {
      "amount": 14000,
      "description": "One year from today. Renews on the day you joined, not in January.",
      "interval": "year",
      "kind": "membership",
      "name": "Producer membership"
    },
    "membership:sponsor": {
      "amount": 4000,
      "description": "One year from today. Renews on the day you joined, not in January.",
      "interval": "year",
      "kind": "membership",
      "name": "Sponsor membership"
    },
    "membership:student": {
      "amount": 6000,
      "description": "One year from today. Renews on the day you joined, not in January.",
      "interval": "year",
      "kind": "membership",
      "name": "Student membership"
    }
  }
};
