# see docs/inline/site/_data/settings.yml.md#1

# see docs/inline/site/_data/settings.yml.md#2
rp_id: ""

# see docs/inline/site/_data/settings.yml.md#3
path: _data/site.yml

# see docs/inline/site/_data/settings.yml.md#4
url: ""

# see docs/inline/site/_data/settings.yml.md#5
