#!/usr/bin/env python3
"""Turn the price list people edit into the one the broker charges from.

WHY THIS EXISTS
---------------
There is exactly one rule that matters when a static site takes money: the
browser must never be able to name a price. A page that posts `amount: 4000`
to a checkout endpoint is a page that can post `amount: 1`, and no amount of
JavaScript on our side changes that, because the JavaScript is theirs.

So the browser sends a SKU — "membership:creator" — and the broker looks the
amount up in a table the browser cannot reach. This script builds that table.

WHERE THE PRICES LIVE, AND WHY IT IS HERE RATHER THAN IN STRIPE
---------------------------------------------------------------
Stripe can hold Price objects, and most integrations put them there. This one
does not, because of something Autumn said while scoping the work: if we sell
memberships as subscriptions, "we would have to be accountable to a flow where
we are announcing our price changes."

Prices in the Stripe dashboard have no such flow. Somebody with a login edits a
number and there is no review, no diff, and no announcement — the first anyone
hears of it is a card statement.

Prices in _data/membership.yml have all three for free. Changing one is a
commit: it shows up in a pull request as a red line and a green line, somebody
approves it, and `git log -p _data/membership.yml` is a complete price history
with dates and names attached. That is the accountability flow, and it already
exists.

Stripe still does the charging. It just does not hold the number — every
Checkout Session is created with an inline `price_data`, so there are no Price
objects to drift from this file.

THE GENERATED FILE IS COMMITTED
-------------------------------
worker/src/prices.js is checked in, because the worker bundles it at deploy
time and Cloudflare's build does not run Python. `--check` fails if it has
drifted from the YAML, which is what CI runs — the same shape as a lock file.

It is a JavaScript module rather than the JSON it obviously wants to be.
Importing JSON needs `with { type: 'json' }` under Node's ESM loader, which
bundlers accept and Node's test runner did not until recently; a module that
exports an object needs no attribute and behaves the same in both.

TODO IS NOT A PRICE
-------------------
Several figures in the data files are the string "TODO", waiting on the board.
Those are skipped rather than defaulted, and the site asks people to get in
touch instead of showing a buy button. A placeholder that becomes a real charge
is the one failure mode here that costs somebody actual money.
"""

import argparse
import json
import pathlib
import sys

import yaml

REPO = pathlib.Path(__file__).resolve().parent.parent
OUT = REPO / "worker" / "src" / "prices.js"

BANNER = """\
// The price list the broker charges from.
//
// GENERATED by script/build-prices.py from _data/membership.yml and
// _data/classes.yml. Do not edit this file — edit those, run the script, and
// commit both. CI fails if the two disagree.
//
// Amounts are in cents, because that is what Stripe takes and because money
// in floating point eventually charges somebody $69.99999.
//
// Changing a price here is a commit, which is the point: `git log -p` on the
// data files is the price history, and a pull request is the announcement.

export default """

# Stripe works in the currency's smallest unit. Dollars never appear below this
# line: money in floating point is a bug waiting for a price that ends in .99.
CENTS = 100


def load(name):
    with open(REPO / "_data" / name, encoding="utf-8") as handle:
        return yaml.safe_load(handle)


def amount(value):
    """Cents, or None if this is not a number somebody has decided yet.

    Accepts int and float because YAML will hand back either depending on how
    the figure was typed, and rejects everything else — "TODO", None, "$40",
    an empty string. Rejecting is the whole job.
    """
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        return None
    if value <= 0:
        return None
    cents = round(value * CENTS)
    # round() on a float can only be trusted this far. Prices are dollars and
    # cents, so anything that does not land on a whole cent was not a price.
    if abs(value * CENTS - cents) > 0.001:
        return None
    return int(cents)


def slug(name):
    return "".join(character.lower() if character.isalnum() else "-" for character in name).strip("-")


def build():
    """The catalog, plus the reasons anything was left out of it."""
    items = {}
    skipped = []

    membership = load("membership.yml")

    for tier in membership.get("tiers") or []:
        cents = amount(tier.get("price"))
        sku = f"membership:{slug(tier['name'])}"
        if cents is None:
            skipped.append(f"{sku} — price is {tier.get('price')!r}")
            continue
        items[sku] = {
            "kind": "membership",
            "name": f"{tier['name']} membership",
            # What the buyer is agreeing to, shown on the Stripe page. The term
            # is the thing people were confused about, so it goes where they
            # are about to spend money rather than only on the page they came
            # from.
            "description": "One year from today. Renews on the day you joined, not in January.",
            "amount": cents,
            # Both are offered for every tier: a single charge covering a year,
            # or the same amount on a yearly subscription. The buyer picks;
            # neither changes what is owed today.
            "interval": "year",
        }

    # Drop-in class attendance. Registration for a course is a different flow
    # with a roster behind it — this is the walk-in who turns up on the night.
    classes = load("classes.yml")
    dropin = classes.get("dropin") or {}
    for who in ("public", "member"):
        cents = amount(dropin.get(who))
        sku = f"class-dropin:{who}"
        if cents is None:
            skipped.append(f"{sku} — price is {dropin.get(who)!r}")
            continue
        items[sku] = {
            "kind": "class",
            "name": f"Class drop-in ({who})",
            "description": "Attendance at one class session.",
            "amount": cents,
            "interval": None,
        }

    return {"currency": "usd", "items": items}, skipped


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if the committed file has drifted from the data files",
    )
    args = parser.parse_args()

    catalog, skipped = build()
    rendered = BANNER + json.dumps(catalog, indent=2, sort_keys=True) + ";\n"

    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != rendered:
            print(
                f"{OUT.relative_to(REPO)} is out of date.\n"
                "A price changed in _data/ without the broker's copy being "
                "rebuilt. Run:\n\n    python3 script/build-prices.py\n\n"
                "and commit the result.",
                file=sys.stderr,
            )
            return 1
        print(f"{OUT.relative_to(REPO)} matches the data files.")
    else:
        OUT.parent.mkdir(parents=True, exist_ok=True)
        OUT.write_text(rendered, encoding="utf-8")
        print(f"Wrote {OUT.relative_to(REPO)} — {len(catalog['items'])} for sale.")

    for note in skipped:
        print(f"  not for sale: {note}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
