#!/usr/bin/env python3
"""Write REDIRECTS.md: every public URL on the Wix site, and where it goes.

The point is provable coverage. It reads the live Wix sitemaps rather than a
list somebody typed, checks each URL against the redirect rules and the built
site, and fails loudly if anything is unaccounted for.

    python3 script/redirect-report.py

Needs network and a built _site/. Run it after `jekyll build`. Not part of CI:
it depends on the old site still being up, and one day it won't be — at which
point this script has done its job and can go.

Wix rate-limits sitemap requests, hence the pacing.
"""

import json
import os
import re
import sys
import time
import urllib.request

HERE = os.path.dirname(__file__)
ROOT = os.path.join(HERE, "..")
SITE = os.path.join(ROOT, "_site")
OUT = os.path.join(ROOT, "REDIRECTS.md")

BASE = "https://www.fcpublicmedia.org"
UA = {"User-Agent": "Mozilla/5.0 (compatible; fcpm-migration-audit/1.0)"}

# Deliberately allowed to 404. See the note in _data/redirects.yml.
DROPPED_PREFIXES = ("/product-page/", "/category/")

GROUP_LABELS = {
    "pages": "Site pages",
    "booking-services": "Booking service pages",
    "event-pages": "Class event pages",
    "store-products": "Store products (never used)",
    "store-categories": "Store categories (never used)",
    "member-profiles_p_first-chunk": "Member profiles",
}


def get(url, attempts=6):
    for i in range(attempts):
        try:
            with urllib.request.urlopen(urllib.request.Request(url, headers=UA), timeout=60) as r:
                return r.read().decode("utf-8", "ignore")
        except Exception as error:
            if i == attempts - 1:
                raise SystemExit(f"Could not fetch {url}: {error}")
            time.sleep(8 * (i + 1))


def path_of(loc):
    return re.sub(r"^https?://(www\.)?fcpublicmedia\.org", "", loc) or "/"


def read_redirects():
    """Parse _data/redirects.yml without requiring PyYAML."""
    rules = {}
    src = None
    for line in open(os.path.join(ROOT, "_data", "redirects.yml")):
        line = line.split("#")[0].rstrip()
        m = re.match(r"^- from:\s*(\S+)", line)
        if m:
            src = m.group(1)
            continue
        m = re.match(r"^\s+to:\s*(\S+)", line)
        if m and src:
            rules[src] = m.group(1)
            src = None
    return rules


def built(path):
    if path == "/":
        return os.path.exists(os.path.join(SITE, "index.html"))
    return os.path.exists(os.path.join(SITE, path.strip("/"), "index.html"))


def main():
    if not os.path.isdir(SITE):
        raise SystemExit("No _site/. Run `bundle exec jekyll build` first.")

    print("Reading the Wix sitemap index...")
    maps = [path_of(l).lstrip("/") for l in re.findall(r"<loc>(.*?)</loc>", get(f"{BASE}/sitemap.xml"))]

    groups = {}
    for m in maps:
        name = m.replace("-sitemap.xml", "")
        time.sleep(6)  # Wix returns 429 without this
        locs = re.findall(r"<loc>(.*?)</loc>", get(f"{BASE}/{m}"))
        groups[name] = sorted({path_of(l) for l in locs})
        print(f"  {name:34} {len(groups[name]):3d}")

    rules = read_redirects()

    rows, gaps, counts = [], [], {"redirect": 0, "kept": 0, "dropped": 0}
    for name, paths in groups.items():
        for p in paths:
            if p in rules:
                rows.append((name, p, rules[p], "Redirected"))
                counts["redirect"] += 1
            elif built(p):
                rows.append((name, p, p, "Same address"))
                counts["kept"] += 1
            elif p.startswith(DROPPED_PREFIXES):
                rows.append((name, p, "—", "Left to 404, on purpose"))
                counts["dropped"] += 1
            else:
                rows.append((name, p, "—", "**UNACCOUNTED FOR**"))
                gaps.append(p)

    total = len(rows)
    with open(OUT, "w") as f:
        f.write(f"""# Redirect record

Every public address on the current Wix site, and where it goes on the new
one. Generated by `script/redirect-report.py`, which reads the live Wix
sitemaps rather than a list anyone typed — so this is a check, not a claim.

**{total} addresses. {counts['redirect']} redirected, {counts['kept']} keep the
same address, {counts['dropped']} deliberately dropped, {len(gaps)} unaccounted for.**

Redirects are permanent (HTTP 301), which tells search engines to move their
records across rather than treat the new address as a duplicate.

They are generated from one file, `_data/redirects.yml`, into both the
Cloudflare and Azure formats — so whichever host the site ends up on, the list
cannot drift.

## The store pages

Thirteen addresses are deliberately left to fail: twelve products and one
category from an online store that was never used. Every one is Wix's own
demo placeholder — the titles are literally "I'm a product".

A 404 is the correct answer for a page that should never have existed: it
tells search engines to forget it. Redirecting them somewhere real would
launder template junk into apparent content.

""")

        if gaps:
            f.write("## ⚠ Unaccounted for\n\nThese have no destination and no decision:\n\n")
            for g in gaps:
                f.write(f"- `{g}`\n")
            f.write("\n")

        for name, paths in groups.items():
            if not paths:
                f.write(f"## {GROUP_LABELS.get(name, name)}\n\nNone published.\n\n")
                continue
            f.write(f"## {GROUP_LABELS.get(name, name)}\n\n")
            f.write("| Old address | Goes to | |\n|---|---|---|\n")
            for g, old, new, status in rows:
                if g == name:
                    f.write(f"| `{old}` | {'—' if new == '—' else '`' + new + '`'} | {status} |\n")
            f.write("\n")

    print(f"\nWrote {OUT}")
    print(f"  {total} addresses: {counts['redirect']} redirected, "
          f"{counts['kept']} unchanged, {counts['dropped']} dropped, {len(gaps)} gaps")

    if gaps:
        print("\nUNACCOUNTED FOR:")
        for g in gaps:
            print("  ", g)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
